### ISSUE TITLE
image not showing properly

### ISSUE THREAD

**Issue by Rj707** [arpitjain03/AJProgressView#3]
the image being used inside the loader circle shows beneath other controls of the ViewController. 
![img_0124](https://user-images.githubusercontent.com/9985642/40906406-1d922408-67fa-11e8-9d37-74b61955bb9a.PNG)

**Comment by arpitjain03** [comment]
Hi Rj707,

For issue lke this, you can set background and corner radius for your the logo View 

In AJProgressView.swift -> func setupAJProgressView() 

Add these 2 lines for innerView
```
innerView.backgroundColor = UIColor.white
innerView.layer.cornerRadius = innerView.frame.size.height/2
```
