### ISSUE TITLE
Image not showing on iphone 11 pro max

### ISSUE THREAD

**Issue by TeamChang** [arpitjain03/AJProgressView#5]
I just downloaded the project and ran it on  iPhone 11 Pro Max
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-29 at 18 45 27](https://user-images.githubusercontent.com/39673702/91640688-192a1080-ea28-11ea-8825-12f433353ed6.png)

This is what it looks like on iPhone 7
![IMG_8046](https://user-images.githubusercontent.com/39673702/91640822-f3513b80-ea28-11ea-939b-a3175ef4f1aa.PNG)

**Comment by arpitjain03** [comment]
Thanks
Issue has been fixed, kindly refer latest code
